### ISSUE TITLE
6.2(Composant d’identification) suggestion

### ISSUE THREAD

**Issue by pierretsap** [SquareBracketAssociates/TinyBlogTutorial#13]
This code doesn't work because gotoAdministration isn't implemented yet and "component" is missing betwin self and gotoAdministration.

  ```
  TBAuthentificationComponent >> validate
  	(self account = 'admin' and: [ self password = 'password' ])
  		ifTrue: [ self gotoAdministration ]
  ```

  The code of this method is missing ```TBAuthentificationComponent >> gotoAdministration```

  Btw this two methods are implemented in the 6.5 section (named "Administration des posts").

**Comment by LucFabresse** [comment]
too old the text changed. Thanks.
