### ISSUE TITLE
 Change class from TBSMagritteReport to TBPostsReport in section 9.8

### ISSUE THREAD

**Issue by ojarsbuddy** [SquareBracketAssociates/TinyBlogTutorial#29]
In section 9.8 the methods described by

TBSMagritteReport >> blog
^ blog

TBSMagritteReport >> blog: aTBBlog
blog := aTBBlog

are better described by

TBPostsReport >> blog
^ blog

TBPostsReport >> blog: aTBBlog
blog := aTBBlog

Created pull requests for this change in both TinyBlog English and TinyBlog Français.

**Comment by Ducasse** [comment]
Thanks!

**Comment by LucFabresse** [comment]
Thanks merged
