### ISSUE TITLE
1.2(Installation de Pharo) suggestion

### ISSUE THREAD

**Issue by pierretsap** [SquareBracketAssociates/TinyBlogTutorial#9]
Maybe we should explain how to install libraries using Pharos's Catalog Browser

**Comment by LucFabresse** [comment]
perhaps in appendix but I am not convinced that this is the right book to explain that

**Comment by LucFabresse** [comment]
definitely not since the idea is too use ready to use image (PharoMooc) from the Pharo Launcher
